# Generated by Django 6.0.6 on 2026-06-13 02:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_numer', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('skills', models.TextField(blank=True, help_text='Comma separated list of skilss')),
                ('availability', models.CharField(blank=True, help_text='e.g., weekends, mornings, afternoons, evenings', max_length=100)),
                ('status', models.BooleanField(default=True, verbose_name='Active')),
                ('joined_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('duration', models.CharField(help_text='in hours', max_length=50)),
                ('required_skills', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_volunteers', models.ManyToManyField(blank=True, related_name='tasks', to='volunteer.volunteer')),
            ],
        ),
    ]
