# Generated by Django 6.0.6 on 2026-06-13 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='volunteer',
            old_name='phone_numer',
            new_name='phone_number',
        ),
    ]
